### ISSUE TITLE
error TS2688: Cannot find type definition file for 'node'.

### ISSUE THREAD

**Issue by feldkurat** [kuschanton/call-gpt#1]
Hmm, seems it doesn't work for me.
```
anand@h:~/works/own/call-gpt$ npm run deploy

> call-gpt@0.0.0 predeploy
> npm run build


> call-gpt@0.0.0 build
> tsc && npm run build:copy-assets

error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point of type library 'node' specified in compilerOptions

  tsconfig.json:11:15
    11     "types": ["node"]
                     ~~~~~~
    File is entry point of type library specified here.


Found 1 error.
```

All environment variables are in .env file; Ubuntu 22.04 / node 18.19.

**Comment by realaidynamics** [comment]
I did 
npm install
and then did
npm run deploy
but the issue im currently getting is that im on an unsupported node.js runtime version being node16 when twilio now apparentl supports node18

**Comment by kuschanton** [comment]
Correct, Twilio Functions now requires node v18, here is migration guide: https://www.twilio.com/docs/serverless/functions-assets/node-upgrade

**Comment by kuschanton** [comment]
I will upgrade the repository at some point

**Comment by kuschanton** [comment]
I have upgraded the project to node 18. Closing this issue.
